export { default as textFillHandler } from './text-fill'
export { default as imageHandler } from './image-fill'
export { default as iconDragHandler } from './icons'
export { default as symbolHandler } from './symbol'
export { default as dragSymbolHandler } from './dragSymbol'
